### ISSUE TITLE
Bookmarks module should have "browser.cmd" and "browser.args" configurable

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/banco#13]
Bookmarks module should have "browser.cmd" (to override `$BROWSER`) and "browser.args" configurable.

Example config section:

```yaml
bookmarks:
    browser:
        cmd: firefox
        args: ["-p", "work-profile"]
```
