### ISSUE TITLE
Add configuration to hide certain labels 

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/banco#16]
For example: hide "done" tasks from the list, or "private" notes. The setting should be override-able with a flag. 

Example configuration files:

```yaml
tasks:
    hide:
       - done
```

```yaml
notes:
      hide:
         - private
```

Example overriding flag:

```sh
banco tasks --show-all
# or
banco tasks --no-hide
```
