### ISSUE TITLE
Local and global config files should be merged

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/banco#20]
Local config file, if exists, should be merged with global.
Local config values should override global.

Global:

```yaml
notes:
    title: $timestamp
    somekey: hello
    otherkey: wow
```

Local:
```yaml
notes:
    somekey: hi
```

Resulting config used by the application:
```yaml
notes:
    title: $timestamp
    somekey: hi
    otherkey: wow
```
