### ISSUE TITLE
Add "shell" command

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/banco#22]
TODO: write description

Just some random notes. It should inject:
- environment variables read from the config file
- environment variables read from an env file (this allows to gitignore this file in case it contains sensitive values)

Idea of config file section:
```yaml
shell:
    env:
        AWS_PROFILE: claudiodangelis
        ARTIFACTORY_API_KEY: 3oh84f
        CGO_ENABLED: 0
```
